# Channels - turn them on or off
channels:
    num_channels: 3  # This needs to match the firmware setting
    states: [1, 0, 0] # 1 for on, 0 for off


# Loop time for outputting data.
#   This is not strictly enforced, but will always be within 10 ms.
#   If set to 0ms, the loop wil run as fast as the control loop.
data_loop_time: 20 #[ms]


#Set the PID Values.
#   If "all_equal" is True, then only the values in "values" are used
#   If "all-equal" is False, then settings for all channels must be specified as a list of lists
PID:
    all_equal: True
    values: [0.5, 0.005, 0.0] #[0.1000, 0.0010, 0.0010]

# Set the max and min pressures in software [psi]
#   If single value, then it will be set for all channels
#   If a vector of length NUM_CHANNELS, then each channel is set independently
max_pressure: 20 # The pressure you never want to exceed (watchdog will prevent higher pressures)
min_pressure: -50

#For debugging purposes
echo: True